/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	time "time"

	unisoundorgv1alpha "github.com/xieydd/kubenetes-crd/pkg/apis/unisound.org/v1alpha"
	versioned "github.com/xieydd/kubenetes-crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/xieydd/kubenetes-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha "github.com/xieydd/kubenetes-crd/pkg/client/listers/unisound.org/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// QueueJobInformer provides access to a shared informer and lister for
// QueueJobs.
type QueueJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha.QueueJobLister
}

type queueJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewQueueJobInformer constructs a new informer for QueueJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewQueueJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredQueueJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredQueueJobInformer constructs a new informer for QueueJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredQueueJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UnisoundV1alpha().QueueJobs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UnisoundV1alpha().QueueJobs(namespace).Watch(options)
			},
		},
		&unisoundorgv1alpha.QueueJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *queueJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredQueueJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *queueJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&unisoundorgv1alpha.QueueJob{}, f.defaultInformer)
}

func (f *queueJobInformer) Lister() v1alpha.QueueJobLister {
	return v1alpha.NewQueueJobLister(f.Informer().GetIndexer())
}
