/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha "github.com/xieydd/kubenetes-crd/pkg/apis/unisound.org/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQueueJobs implements QueueJobInterface
type FakeQueueJobs struct {
	Fake *FakeUnisoundV1alpha
	ns   string
}

var queuejobsResource = schema.GroupVersionResource{Group: "unisound.org", Version: "v1alpha", Resource: "queuejobs"}

var queuejobsKind = schema.GroupVersionKind{Group: "unisound.org", Version: "v1alpha", Kind: "QueueJob"}

// Get takes name of the queueJob, and returns the corresponding queueJob object, and an error if there is any.
func (c *FakeQueueJobs) Get(name string, options v1.GetOptions) (result *v1alpha.QueueJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(queuejobsResource, c.ns, name), &v1alpha.QueueJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.QueueJob), err
}

// List takes label and field selectors, and returns the list of QueueJobs that match those selectors.
func (c *FakeQueueJobs) List(opts v1.ListOptions) (result *v1alpha.QueueJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(queuejobsResource, queuejobsKind, c.ns, opts), &v1alpha.QueueJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.QueueJobList{ListMeta: obj.(*v1alpha.QueueJobList).ListMeta}
	for _, item := range obj.(*v1alpha.QueueJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested queueJobs.
func (c *FakeQueueJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(queuejobsResource, c.ns, opts))

}

// Create takes the representation of a queueJob and creates it.  Returns the server's representation of the queueJob, and an error, if there is any.
func (c *FakeQueueJobs) Create(queueJob *v1alpha.QueueJob) (result *v1alpha.QueueJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(queuejobsResource, c.ns, queueJob), &v1alpha.QueueJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.QueueJob), err
}

// Update takes the representation of a queueJob and updates it. Returns the server's representation of the queueJob, and an error, if there is any.
func (c *FakeQueueJobs) Update(queueJob *v1alpha.QueueJob) (result *v1alpha.QueueJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(queuejobsResource, c.ns, queueJob), &v1alpha.QueueJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.QueueJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQueueJobs) UpdateStatus(queueJob *v1alpha.QueueJob) (*v1alpha.QueueJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(queuejobsResource, "status", c.ns, queueJob), &v1alpha.QueueJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.QueueJob), err
}

// Delete takes name of the queueJob and deletes it. Returns an error if one occurs.
func (c *FakeQueueJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(queuejobsResource, c.ns, name), &v1alpha.QueueJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQueueJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(queuejobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha.QueueJobList{})
	return err
}

// Patch applies the patch and returns the patched queueJob.
func (c *FakeQueueJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.QueueJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(queuejobsResource, c.ns, name, data, subresources...), &v1alpha.QueueJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.QueueJob), err
}
